### PR TITLE
make operator new inline to avoid duplicates during linking

### PR DESCRIPTION
**Pull request by mo22**

### CODE REVIEW

**Comment by domschl** [comment]
Which platform define did you use?

Some arduino SDKs do define a `new` operator and others don't. This is currently handled a a feature-define `USTD_FEATURE_SUPPORTS_NEW_OPERATOR`, so that platforms that have a `new` operator implementation simply define this.
Making this inline effectively causes to different `new` implementations without the compiler noticing, so that could be problematic.

**Comment by mo22** [comment]
Hi, I'm using platformio + Arduino nano, which does not have that operator defined.

The issue is that if you have two cpp files (a.cpp and b.cpp) that both include functional.h you'll end up with two instances of that operator implementation causing a linker error.

Defining that function inline prevents that. An alternative would be to just have the prototype in the header file and move the implementation to a c file.

**Comment by domschl** [comment]
Hmm. That's a valid point.
A hacky solution would be to `#define USTD_FEATURE_SUPPORTS_NEW_OPERATOR` in one of the cpp files before including `ustd_functional.h`.
Need to think about this more.

**Comment by domschl** [comment]
I guess you're right, it's going to be `inline`.
This problem also affects other global functions e.g. in `ustd_platform.h`.
I've to investigate the extend a bit more...

**Comment by domschl** [comment]
Release 0.6.2 is published in platformio, thank you!

**Comment by mo22** [comment]
Thank you very much, greatly appreciated!

**Pull request merged**
